// Generated by CoffeeScript 1.6.3
(function() {
  var CXLTX, MULTIMIX, ids_provider, provider, sample_provider;

  CXLTX = require('./main');

  MULTIMIX = require('coffeenode-multimix');

  sample_provider = require('./sample-provider');

  ids_provider = require('./ids-provider');

  provider = MULTIMIX.compose(sample_provider, ids_provider);

  this.main = function() {
    var command, ignored, parameter, splitter, texroute, _ref;
    _ref = process.argv, ignored = _ref[0], ignored = _ref[1], texroute = _ref[2], splitter = _ref[3], command = _ref[4], parameter = _ref[5];
    CXLTX.dispatch(provider, texroute, splitter, command, parameter, (function(_this) {
      return function(error, result) {
        if (error != null) {
          CXLTX.echo(CXLTX.debug(error));
        }
        if (result != null) {
          return CXLTX.echo(result);
        }
      };
    })(this));
    return null;
  };

  this.main();

}).call(this);
