// Generated by CoffeeScript 1.6.3
(function() {
  var CXLTX, MULTIMIX, ids_provider, provider, sample_provider;

  CXLTX = require('./main');

  MULTIMIX = require('coffeenode-multimix');

  sample_provider = require('./sample-provider');

  ids_provider = require('./ids-provider');

  provider = MULTIMIX.compose(sample_provider, ids_provider);

  this.main = function() {
    var command, jobname, parameter, splitter, texroute;
    texroute = process.argv[2];
    jobname = process.argv[3];
    splitter = process.argv[4];
    command = process.argv[5];
    parameter = process.argv[6];
    CXLTX.dispatch(provider, texroute, jobname, splitter, command, parameter, (function(_this) {
      return function(error, result) {
        if (error != null) {
          CXLTX.echo(CXLTX.debug(error));
        }
        if (result != null) {
          return CXLTX.echo(result);
        }
      };
    })(this));
    return null;
  };

  this.main();

}).call(this);
